//
//  VideoTableViewCellConstants.h
//  Shelby
//
//  Created by Mark Johnson on 10/18/11.
//  Copyright 2011 Shelby.tv. All rights reserved.
//

#define IPAD_CELL_WIDTH 330
#define IPAD_CELL_HEIGHT 232

#define IPAD_VIDEO_WIDTH 290
#define IPAD_VIDEO_HEIGHT 163

#define IPAD_BADGE_WIDTH 33
#define IPAD_BADGE_HEIGHT 33

#define IPAD_VIDEO_FOOTER_ORIGIN_X 0
#define IPAD_VIDEO_FOOTER_ORIGIN_Y 163
#define IPAD_VIDEO_FOOTER_WIDTH 290
#define IPAD_VIDEO_FOOTER_HEIGHT 29

#define IPAD_SHARER_ORIGIN_X 2
#define IPAD_SHARER_ORIGIN_Y 166
#define IPAD_SHARER_WIDTH 24
#define IPAD_SHARER_HEIGHT 24

#define IPAD_SHARER_NAME_ORIGIN_X 30
#define IPAD_SHARER_NAME_ORIGIN_Y 168
#define IPAD_SHARER_NAME_WIDTH 157
#define IPAD_SHARER_NAME_HEIGHT 21

#define IPAD_SHARETIME_ORIGIN_X 190
#define IPAD_SHARETIME_ORIGIN_Y 168
#define IPAD_SHARETIME_WIDTH 94
#define IPAD_SHARETIME_HEIGHT 21

#define IPAD_CELL_HORIZ_MARGIN 20
#define IPAD_CELL_VERT_MARGIN 20

#define IPAD_COMMENT_ORIGIN_X 12
#define IPAD_COMMENT_ORIGIN_Y 132
#define IPAD_COMMENT_WIDTH 266
#define IPAD_COMMENT_HEIGHT 24

#define IPAD_COMMENT_VIEW_ORIGIN_X 0
#define IPAD_COMMENT_VIEW_ORIGIN_Y 125
#define IPAD_COMMENT_VIEW_WIDTH 290
#define IPAD_COMMENT_VIEW_HEIGHT 38

#define IPAD_EXPANDED_COMMENT_MARGIN 10


#define IPHONE_CELL_HORIZ_MARGIN 20
#define IPHONE_CELL_VERT_MARGIN 10

#define IPHONE_CELL_WIDTH 320
#define IPHONE_CELL_HEIGHT 118

#define IPHONE_VIDEO_WIDTH 121
#define IPHONE_VIDEO_HEIGHT 69

#define IPHONE_BADGE_WIDTH 33
#define IPHONE_BADGE_HEIGHT 33

#define IPHONE_COMMENT_VIEW_ORIGIN_X 121
#define IPHONE_COMMENT_VIEW_ORIGIN_Y 10
#define IPHONE_COMMENT_VIEW_WIDTH 159
#define IPHONE_COMMENT_VIEW_HEIGHT 69

#define IPHONE_VIDEO_FOOTER_ORIGIN_X 20
#define IPHONE_VIDEO_FOOTER_ORIGIN_Y 69
#define IPHONE_VIDEO_FOOTER_WIDTH 280
#define IPHONE_VIDEO_FOOTER_HEIGHT 29

#define IPHONE_SHARER_ORIGIN_X 2
#define IPHONE_SHARER_ORIGIN_Y 71
#define IPHONE_SHARER_WIDTH 24
#define IPHONE_SHARER_HEIGHT 24

#define IPHONE_COMMENT_ORIGIN_X 128
#define IPHONE_COMMENT_ORIGIN_Y 7
#define IPHONE_COMMENT_WIDTH 145
#define IPHONE_COMMENT_HEIGHT 55

#define IPHONE_SHARER_NAME_ORIGIN_X 30
#define IPHONE_SHARER_NAME_ORIGIN_Y 74
#define IPHONE_SHARER_NAME_WIDTH 147
#define IPHONE_SHARER_NAME_HEIGHT 21

#define IPHONE_SHARETIME_ORIGIN_X 179
#define IPHONE_SHARETIME_ORIGIN_Y 74
#define IPHONE_SHARETIME_WIDTH 94
#define IPHONE_SHARETIME_HEIGHT 21